# Generated by Django 6.0.7 on 2026-07-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapping',
            options={'ordering': ['-assigned_at'], 'verbose_name_plural': 'mappings'},
        ),
    ]
